server:
  port: 8010

---
spring:
  profiles: primary

server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/,http://localhost:8013/eureka/
      
---
spring:
  profiles: secondry

server:
  port: 8012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: tertiary

server:
  port: 8013

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/