---
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: sentence
  application:
    name: eureka-client-sentence-one-app-sentence
server:
  port: 8020
words: NotApplicable

---
spring:
  profiles: subject
  application:
    name: eureka-client-sentence-one-app-subject
#words: I,You,He,She,It
words: They

---
spring:
  profiles: verb
  application:
    name: eureka-client-sentence-one-app-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: eureka-client-sentence-one-app-article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: eureka-client-sentence-one-app-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: eureka-client-sentence-one-app-noun
words: boat,book,vote,seat,backpack,partition,groundhog
